# SPDX-FileCopyrightText: © 2025 Authors of the ROAR-NET API Specification <https://github.com/roar-net/roar-net-api-spec/blob/main/AUTHORS>
#
# SPDX-License-Identifier: Apache-2.0

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: d174eb7a8f35e05d4065c82d375ad84aa0b32352  # frozen: v0.17.2
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/fsfe/reuse-tool
  rev: 60dfc6b2ad9e1f3eabfbcf3a0dc202ee89dc5a00  # frozen: v5.0.2
  hooks:
    - id: reuse
